import { 
  Organization, 
  UserProfile, 
  Household, 
  CollectionItem, 
  Collector, 
  Vehicle, 
  ProcessingFacility, 
  WasteBatch, 
  Recycler, 
  RecyclingTransaction, 
  Complaint, 
  IoTDevice, 
  AuditLog,
  MarketplaceListing,
  MarketplaceOffer,
  MarketplaceAuctionBid,
  MarketplaceOrder,
  MaterialDispute,
  MarketplaceReview,
  Zone
} from '../types';

export const INITIAL_ZONES: Zone[] = [
  { id: 'z1', organization_id: 'org-swarnandhra', name: 'Zone 1 — Campus North Hostel', code: 'Z-01', risk_level: 'LOW' },
  { id: 'z2', organization_id: 'org-swarnandhra', name: 'Zone 2 — Tech Block & Labs', code: 'Z-02', risk_level: 'MEDIUM' },
  { id: 'z3', organization_id: 'org-swarnandhra', name: 'Zone 3 — Cafeteria & Food Court', code: 'Z-03', risk_level: 'HIGH' }
];

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-swarnandhra',
    name: 'Swarnandhra Engineering College',
    type: 'College / University',
    category_label: 'College / University',
    icon_name: 'GraduationCap',
    slug: 'swarnandhra-tech',
    contact_email: 'facilities@swarnandhra.ac.in',
    subscription_plan: 'enterprise',
    is_active: true,
    created_at: '2026-01-10T08:00:00Z',
  },
  {
    id: 'org-eco-restaurant',
    name: 'Grand Palace Hotel & Resort',
    type: 'Hotel',
    category_label: 'Hotel / Hospitality',
    icon_name: 'Utensils',
    slug: 'eco-restaurant',
    contact_email: 'sustainability@grandpalace.com',
    subscription_plan: 'professional',
    is_active: true,
    created_at: '2026-02-01T09:30:00Z',
  },
  {
    id: 'org-metro-office',
    name: 'Metro Commercial Hub',
    type: 'Commercial Building',
    category_label: 'Commercial Building',
    icon_name: 'Building2',
    slug: 'metro-office',
    contact_email: 'ops@metrotower.com',
    subscription_plan: 'professional',
    is_active: true,
    created_at: '2026-03-05T10:15:00Z',
  },
  {
    id: 'org-green-valley',
    name: 'Green Valley Municipality',
    type: 'Municipality',
    category_label: 'Municipality',
    icon_name: 'Landmark',
    slug: 'green-valley',
    contact_email: 'contact@greenvalley.gov.in',
    subscription_plan: 'enterprise',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'org-sunshine-residence',
    name: 'Sunshine Residential Community',
    type: 'Residential Community',
    category_label: 'Residential Community',
    icon_name: 'Home',
    slug: 'sunshine-residence',
    contact_email: 'hoa@sunshineresidence.com',
    subscription_plan: 'starter',
    is_active: true,
    created_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'org-apollo-hospital',
    name: 'Apollo General Hospital',
    type: 'Hospital',
    category_label: 'Hospital / Medical',
    icon_name: 'Cross',
    slug: 'apollo-hospital',
    contact_email: 'waste@apollohospital.org',
    subscription_plan: 'enterprise',
    is_active: true,
    created_at: '2026-03-01T11:00:00Z',
  }
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-citizen-1',
    organization_id: 'org-swarnandhra',
    role: 'citizen',
    full_name: 'Priya Sharma (Campus Resident)',
    email: 'priya.sharma@swarnandhra.ac.in',
    phone: '+91 98765 43210',
    is_verified: true,
  },
  {
    id: 'usr-citizen-2',
    organization_id: 'org-sunshine-residence',
    role: 'citizen',
    full_name: 'Anita Patel (Sector 2 Resident)',
    email: 'anita.patel@sunshineresidence.com',
    phone: '+91 98222 11111',
    is_verified: true,
  },
  {
    id: 'usr-citizen-3',
    organization_id: 'org-eco-restaurant',
    role: 'citizen',
    full_name: 'Rajesh Verma (Grand Resort Kitchen Head)',
    email: 'rajesh.verma@grandpalace.com',
    phone: '+91 97333 44444',
    is_verified: true,
  },
  {
    id: 'usr-collector-1',
    organization_id: 'org-swarnandhra',
    role: 'collector',
    full_name: 'Ramesh Kumar (Zone 1 Fleet)',
    email: 'ramesh.collector@wasteloop.org',
    phone: '+91 91234 56789',
    is_verified: true,
  },
  {
    id: 'usr-collector-2',
    organization_id: 'org-green-valley',
    role: 'collector',
    full_name: 'Suresh Rao (Zone 2 Heavy Tipper)',
    email: 'suresh.collector@wasteloop.org',
    phone: '+91 92345 67890',
    is_verified: true,
  },
  {
    id: 'usr-supervisor-1',
    organization_id: 'org-swarnandhra',
    role: 'supervisor',
    full_name: 'Anil Verma (Eco Operations Head)',
    email: 'anil.verma@swarnandhra.ac.in',
    phone: '+91 98888 77777',
    is_verified: true,
  },
  {
    id: 'usr-admin-1',
    organization_id: 'org-swarnandhra',
    role: 'admin',
    full_name: 'Dr. Sarah Jenkins (Sustainability Director)',
    email: 'sarah.jenkins@swarnandhra.ac.in',
    phone: '+91 94444 33333',
    is_verified: true,
  },
  {
    id: 'usr-recycler-1',
    organization_id: 'org-swarnandhra',
    role: 'recycler',
    full_name: 'Vikram Mehta (CleanTech Recyclers)',
    email: 'vikram@cleantechrecycling.in',
    phone: '+91 97777 22222',
    is_verified: true,
  },
  {
    id: 'usr-platform-1',
    organization_id: 'org-swarnandhra',
    role: 'platform_admin',
    full_name: 'WasteLoop Platform Master',
    email: 'u638126@gmail.com',
    phone: '+1 800 555 WASTELOOP',
    is_verified: true,
  }
];

export const INITIAL_HOUSEHOLDS: Household[] = [
  {
    id: 'hh-101',
    organization_id: 'org-swarnandhra',
    user_id: 'usr-citizen-1',
    zone_id: 'zone-1',
    address: 'Swarnandhra Hostel Block 4, Campus Sector 1',
    latitude: 16.5412,
    longitude: 81.5245,
    qr_code_token: 'WL-CAMPUS-101-9982',
  },
  {
    id: 'hh-102',
    organization_id: 'org-eco-restaurant',
    user_id: 'usr-citizen-3',
    zone_id: 'zone-2',
    address: 'Grand Eco Resort Central Kitchen & Dining Hall',
    latitude: 16.5435,
    longitude: 81.5280,
    qr_code_token: 'WL-REST-102-4411',
  },
  {
    id: 'hh-103',
    organization_id: 'org-metro-office',
    zone_id: 'zone-3',
    address: 'Metro Corporate Tower Floor 12 Cafeteria & Printing Hub',
    latitude: 16.5480,
    longitude: 81.5310,
    qr_code_token: 'WL-OFFICE-103-7720',
  },
  {
    id: 'hh-104',
    organization_id: 'org-sunshine-residence',
    user_id: 'usr-citizen-2',
    zone_id: 'zone-1',
    address: 'Sunshine Enclave Apartment 402, Sector 2',
    latitude: 16.5420,
    longitude: 81.5260,
    qr_code_token: 'WL-RES-104-5590',
  }
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-01',
    organization_id: 'org-swarnandhra',
    registration_number: 'AP-37-EV-101',
    type: 'Electric Tipper LCV (2-Ton)',
    capacity_kg: 2000,
    current_load_kg: 1250,
    status: 'on_route',
    assigned_collector_name: 'Ramesh Kumar',
  },
  {
    id: 'veh-02',
    organization_id: 'org-swarnandhra',
    registration_number: 'AP-37-T-4912',
    type: 'Compactor Truck (5-Ton)',
    capacity_kg: 5000,
    current_load_kg: 3200,
    status: 'available',
    assigned_collector_name: 'Suresh Patel',
  }
];

export const INITIAL_COLLECTORS: Collector[] = [
  {
    id: 'col-01',
    organization_id: 'org-swarnandhra',
    user_id: 'usr-collector-1',
    badge_number: 'WL-COL-804',
    name: 'Ramesh Kumar',
    shift_status: 'on_duty',
    assigned_vehicle_id: 'veh-01',
    current_latitude: 16.5420,
    current_longitude: 81.5255,
    completed_tasks_today: 14,
    remaining_tasks_today: 4,
  }
];

export const INITIAL_FACILITIES: ProcessingFacility[] = [
  {
    id: 'fac-01',
    organization_id: 'org-swarnandhra',
    name: 'Swarnandhra Campus Biomass & Composting Unit',
    type: 'composting_plant',
    address: 'Eco Park Zone, Swarnandhra Campus',
    latitude: 16.5510,
    longitude: 81.5400,
    daily_capacity_tons: 25,
  },
  {
    id: 'fac-02',
    organization_id: 'org-swarnandhra',
    name: 'Central Material Recovery Facility (MRF)',
    type: 'mrf',
    address: 'Industrial Development Area',
    latitude: 16.5380,
    longitude: 81.5150,
    daily_capacity_tons: 80,
  }
];

export const INITIAL_COLLECTIONS: CollectionItem[] = [
  {
    id: 'col-task-01',
    organization_id: 'org-swarnandhra',
    household_id: 'hh-101',
    collector_id: 'col-01',
    vehicle_id: 'veh-01',
    zone_id: 'zone-1',
    type: 'normal',
    waste_category: 'dry_recyclable',
    scheduled_window_start: '2026-09-10T07:00:00Z',
    scheduled_window_end: '2026-09-10T09:00:00Z',
    status: 'collected',
    priority: 'medium',
    priority_reason: 'Regular morning scheduled collection route',
    estimated_weight_kg: 6.0,
    actual_weight_kg: 8.5,
    segregation_verified: true,
    household_address: 'Swarnandhra Hostel Block 4, Campus Sector 1',
    collector_name: 'Ramesh Kumar',
    vehicle_reg: 'AP-37-EV-101',
    created_at: '2026-09-10T06:00:00Z',
    updated_at: '2026-09-10T08:15:00Z',
  },
  {
    id: 'col-task-02',
    organization_id: 'org-swarnandhra',
    household_id: 'hh-102',
    collector_id: 'col-01',
    vehicle_id: 'veh-01',
    zone_id: 'zone-2',
    type: 'normal',
    waste_category: 'wet_organic',
    scheduled_window_start: '2026-09-10T07:00:00Z',
    scheduled_window_end: '2026-09-10T09:00:00Z',
    status: 'collector_en_route',
    priority: 'high',
    priority_reason: 'HIGH — Cafeteria organic waste velocity high',
    estimated_weight_kg: 24.0,
    household_address: 'Swarnandhra Central Cafeteria Kitchen',
    collector_name: 'Ramesh Kumar',
    vehicle_reg: 'AP-37-EV-101',
    created_at: '2026-09-10T06:00:00Z',
    updated_at: '2026-09-10T08:45:00Z',
  },
  {
    id: 'col-task-03',
    organization_id: 'org-swarnandhra',
    household_id: 'hh-103',
    zone_id: 'zone-1',
    type: 'special',
    waste_category: 'e_waste',
    scheduled_window_start: '2026-09-10T10:00:00Z',
    scheduled_window_end: '2026-09-10T12:00:00Z',
    status: 'requested',
    priority: 'critical',
    priority_reason: 'CRITICAL — Computer Science Lab old hardware e-waste',
    estimated_weight_kg: 65.0,
    household_address: 'Swarnandhra IT Lab Block C',
    created_at: '2026-09-10T07:30:00Z',
    updated_at: '2026-09-10T07:30:00Z',
  }
];

export const INITIAL_WASTE_BATCHES: WasteBatch[] = [
  {
    id: 'wb-001',
    batch_code: 'WL-2026-000184',
    organization_id: 'org-swarnandhra',
    collection_id: 'col-task-01',
    waste_category: 'dry_recyclable',
    actual_weight_kg: 150.0,
    collected_weight_kg: 150.0,
    facility_received_weight_kg: 150.0,
    recycler_received_weight_kg: 146.5,
    recovered_weight_kg: 75.0,
    weight_discrepancy_kg: 3.5,
    collector_id: 'col-01',
    collector_name: 'Ramesh Kumar',
    vehicle_id: 'veh-01',
    processing_facility_id: 'fac-01',
    processing_facility_name: 'Central Material Recovery Facility (MRF)',
    coarse_separation_status: 'completed',
    organic_fraction_kg: 60.0,
    dry_fraction_kg: 75.0,
    special_fraction_kg: 5.0,
    residual_fraction_kg: 10.0,
    recycler_id: 'rec-01',
    recycler_name: 'CleanTech Materials & Plastics',
    final_status: 'RECYCLED',
    current_location_name: 'CleanTech Eco Polymers Facility, Sector 5',
    current_latitude: 16.5380,
    current_longitude: 81.5150,
    current_responsible_entity: 'CleanTech Materials & Plastics',
    last_updated_at: '2026-09-10T14:30:00Z',
    created_at: '2026-09-10T08:00:00Z',
    events: [
      {
        id: 'ev-101',
        batch_id: 'wb-001',
        batch_code: 'WL-2026-000184',
        event_type: 'SOURCE',
        new_status: 'SOURCE',
        timestamp: '2026-09-10T08:00:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'Priya Sharma (Campus Resident)',
        actor_role: 'citizen',
        location_name: 'Swarnandhra Hostel Block 4, Campus Sector 1',
        latitude: 16.5450,
        longitude: 81.5280,
        weight_kg: 150.0,
        notes: 'Dry Recyclables segregated and ready at collection point'
      },
      {
        id: 'ev-102',
        batch_id: 'wb-001',
        batch_code: 'WL-2026-000184',
        event_type: 'COLLECTED',
        previous_status: 'SOURCE',
        new_status: 'COLLECTED',
        timestamp: '2026-09-10T08:30:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'Ramesh Kumar',
        actor_role: 'collector',
        location_name: 'Swarnandhra Hostel Block 4',
        latitude: 16.5450,
        longitude: 81.5280,
        collector_id: 'col-01',
        vehicle_id: 'veh-01',
        weight_kg: 150.0,
        notes: 'Scale verified. Purity verified Grade A.'
      },
      {
        id: 'ev-103',
        batch_id: 'wb-001',
        batch_code: 'WL-2026-000184',
        event_type: 'IN_TRANSIT',
        previous_status: 'COLLECTED',
        new_status: 'IN_TRANSIT',
        timestamp: '2026-09-10T09:00:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'Ramesh Kumar',
        actor_role: 'collector',
        location_name: 'Campus Main Transit Route',
        latitude: 16.5420,
        longitude: 81.5255,
        vehicle_id: 'veh-01',
        weight_kg: 150.0,
        notes: 'En route to Central MRF Facility'
      },
      {
        id: 'ev-104',
        batch_id: 'wb-001',
        batch_code: 'WL-2026-000184',
        event_type: 'ARRIVED_AT_FACILITY',
        previous_status: 'IN_TRANSIT',
        new_status: 'ARRIVED_AT_FACILITY',
        timestamp: '2026-09-10T09:45:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'Central MRF Gate Scale',
        actor_role: 'facility_operator',
        location_name: 'Central Material Recovery Facility (MRF)',
        latitude: 16.5380,
        longitude: 81.5150,
        weight_kg: 150.0,
        notes: 'Weighbridge check pass: 150 kg verified'
      },
      {
        id: 'ev-105',
        batch_id: 'wb-001',
        batch_code: 'WL-2026-000184',
        event_type: 'SEGREGATION',
        previous_status: 'ARRIVED_AT_FACILITY',
        new_status: 'SEGREGATION',
        timestamp: '2026-09-10T10:30:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'Coarse Separation Team A',
        actor_role: 'facility_operator',
        location_name: 'Central Material Recovery Facility (MRF)',
        latitude: 16.5380,
        longitude: 81.5150,
        weight_kg: 150.0,
        notes: 'Coarse sorting completed: Organic=60kg, Dry=75kg, Special=5kg, Residual=10kg'
      },
      {
        id: 'ev-106',
        batch_id: 'wb-001',
        batch_code: 'WL-2026-000184',
        event_type: 'ASSIGNED_TO_RECYCLER',
        previous_status: 'SEGREGATION',
        new_status: 'ASSIGNED_TO_RECYCLER',
        timestamp: '2026-09-10T11:15:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'Anil Verma (Supervisor)',
        actor_role: 'supervisor',
        location_name: 'Central Material Recovery Facility (MRF)',
        recycler_id: 'rec-01',
        weight_kg: 75.0,
        notes: 'Assigned 75 kg Dry Recyclables to CleanTech Materials & Plastics'
      },
      {
        id: 'ev-107',
        batch_id: 'wb-001',
        batch_code: 'WL-2026-000184',
        event_type: 'ACCEPTED_BY_RECYCLER',
        previous_status: 'ASSIGNED_TO_RECYCLER',
        new_status: 'ACCEPTED_BY_RECYCLER',
        timestamp: '2026-09-10T12:00:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'CleanTech Dispatcher',
        actor_role: 'recycler',
        location_name: 'CleanTech Eco Polymers Facility, Sector 5',
        recycler_id: 'rec-01',
        weight_kg: 146.5,
        notes: 'Accepted. Weighbridge noted 3.5 kg discrepancy due to moisture loss.',
        weight_discrepancy_flag: true
      },
      {
        id: 'ev-108',
        batch_id: 'wb-001',
        batch_code: 'WL-2026-000184',
        event_type: 'RECYCLED',
        previous_status: 'ACCEPTED_BY_RECYCLER',
        new_status: 'RECYCLED',
        timestamp: '2026-09-10T14:30:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'CleanTech Processing Unit 2',
        actor_role: 'recycler',
        location_name: 'CleanTech Eco Polymers Facility, Sector 5',
        recycler_id: 'rec-01',
        weight_kg: 75.0,
        notes: 'Processed into high-purity recycled rPET flakes & certified.'
      }
    ]
  },
  {
    id: 'wb-002',
    batch_code: 'WL-2026-000299',
    organization_id: 'org-swarnandhra',
    collection_id: 'col-task-02',
    waste_category: 'wet_organic',
    actual_weight_kg: 45.0,
    collected_weight_kg: 45.0,
    collector_id: 'col-01',
    collector_name: 'Ramesh Kumar',
    vehicle_id: 'veh-01',
    coarse_separation_status: 'pending',
    organic_fraction_kg: 0,
    dry_fraction_kg: 0,
    special_fraction_kg: 0,
    residual_fraction_kg: 0,
    final_status: 'IN_TRANSIT',
    current_location_name: 'Campus Transit Sector 2 En Route to Biomass Facility',
    current_latitude: 16.5420,
    current_longitude: 81.5255,
    current_responsible_entity: 'Vehicle AP-37-EV-101 (Ramesh Kumar)',
    last_updated_at: '2026-09-11T05:00:00Z',
    created_at: '2026-09-11T04:15:00Z',
    events: [
      {
        id: 'ev-201',
        batch_id: 'wb-002',
        batch_code: 'WL-2026-000299',
        event_type: 'SOURCE',
        new_status: 'SOURCE',
        timestamp: '2026-09-11T04:15:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'Swarnandhra Central Cafeteria Kitchen',
        actor_role: 'citizen',
        location_name: 'Cafeteria Kitchen Loading Dock',
        latitude: 16.5490,
        longitude: 81.5310,
        weight_kg: 45.0,
        notes: 'Wet organic food waste packed in bio-bins'
      },
      {
        id: 'ev-202',
        batch_id: 'wb-002',
        batch_code: 'WL-2026-000299',
        event_type: 'COLLECTED',
        previous_status: 'SOURCE',
        new_status: 'COLLECTED',
        timestamp: '2026-09-11T04:45:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'Ramesh Kumar',
        actor_role: 'collector',
        location_name: 'Cafeteria Kitchen Loading Dock',
        latitude: 16.5490,
        longitude: 81.5310,
        collector_id: 'col-01',
        vehicle_id: 'veh-01',
        weight_kg: 45.0,
        notes: 'Collected and logged into EV Tipper'
      },
      {
        id: 'ev-203',
        batch_id: 'wb-002',
        batch_code: 'WL-2026-000299',
        event_type: 'IN_TRANSIT',
        previous_status: 'COLLECTED',
        new_status: 'IN_TRANSIT',
        timestamp: '2026-09-11T05:00:00Z',
        organization_id: 'org-swarnandhra',
        actor_name: 'Ramesh Kumar',
        actor_role: 'collector',
        location_name: 'Campus Transit Sector 2 En Route to Biomass Facility',
        latitude: 16.5420,
        longitude: 81.5255,
        vehicle_id: 'veh-01',
        weight_kg: 45.0,
        notes: 'Active transport to Campus Biomass Unit'
      }
    ]
  }
];

export const INITIAL_RECYCLERS: Recycler[] = [
  {
    id: 'rec-01',
    organization_id: 'org-swarnandhra',
    company_name: 'CleanTech Materials & Plastics',
    verification_status: 'verified',
    accepted_materials: ['PET Plastics', 'HDPE Containers', 'Corrugated Cardboard', 'Aluminium Cans'],
    service_area: 'Swarnandhra Region',
    capacity_kg_per_day: 10000,
    contact_phone: '+91 97777 22222',
    rating: 4.9,
  }
];

export const INITIAL_RECYCLING_TRANSACTIONS: RecyclingTransaction[] = [
  {
    id: 'tx-001',
    organization_id: 'org-swarnandhra',
    waste_batch_id: 'wb-001',
    batch_code: 'WL-2026-000184',
    recycler_id: 'rec-01',
    recycler_name: 'CleanTech Materials & Plastics',
    material_type: 'Sorted Dry Recyclables (75 kg)',
    weight_kg: 75.0,
    agreed_value_usd: 24.50,
    status: 'completed',
    created_at: '2026-09-10T10:00:00Z',
  }
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-101',
    ticket_code: 'TKT-88491',
    organization_id: 'org-swarnandhra',
    household_id: 'hh-101',
    user_id: 'usr-citizen-1',
    reporter_name: 'Priya Sharma',
    category: 'missed_collection',
    severity: 'high',
    description: 'Scheduled morning pickup window (7:00 - 9:00 AM) ended without collector confirmation.',
    status: 'assigned',
    assigned_supervisor_name: 'Anil Verma',
    is_auto_escalated: true,
    created_at: '2026-09-10T09:05:00Z',
  }
];

export const INITIAL_IOT_DEVICES: IoTDevice[] = [
  {
    id: 'iot-01',
    device_code: 'BIN-104-CAFETERIA',
    organization_id: 'org-swarnandhra',
    zone_name: 'Swarnandhra Campus Zone 1',
    location_name: 'Campus Cafeteria Waste Bin',
    latitude: 16.5430,
    longitude: 81.5260,
    fill_level_percent: 86,
    battery_level_percent: 94,
    temperature_celsius: 28.5,
    last_ping: '2026-09-10T13:30:00Z',
    status: 'overflow_imminent',
    predicted_overflow_hours: 4.5,
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-01',
    organization_id: 'org-swarnandhra',
    user_name: 'Ramesh Kumar',
    role: 'collector',
    action: 'COLLECTION_COMPLETED',
    entity_type: 'CollectionTask',
    entity_id: 'col-task-01',
    details: 'Actual weight recorded: 8.5 kg. Segregation verified.',
    timestamp: '2026-09-10T08:15:00Z',
  }
];

export const INITIAL_MARKETPLACE_LISTINGS: MarketplaceListing[] = [
  {
    id: 'mkt-lst-01',
    seller_id: 'usr-recycler-1',
    seller_name: 'CleanTech Eco Polymers',
    seller_org_name: 'CleanTech Materials & Plastics',
    seller_rating: 4.9,
    seller_trust_rating: 4.9,
    title: 'High-Density Polyethylene (HDPE) Recycled Flakes',
    category: 'Plastics',
    description: 'Washed, sorted, and shredded HDPE blue/white grade flakes from post-consumer beverage caps and bottles. Melt Flow Index: 0.8g/10min.',
    images: [
      'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&w=800&q=80'
    ],
    quantity: 4500,
    unit: 'kg',
    quality_grade: 'Grade A',
    price_per_unit: 0.85,
    sale_type: 'direct_sale',
    location_zone: 'Swarnandhra Campus Zone 1',
    availability_date: '2026-09-15',
    status: 'active',
    verification_status: 'verified',
    authenticity_score: 98,
    batch_code: 'WL-MKT-2026-881',
    views_count: 142,
    created_at: '2026-09-08T10:00:00Z'
  },
  {
    id: 'mkt-lst-02',
    seller_id: 'usr-supervisor-1',
    seller_name: 'Anil Verma (Facilities Head)',
    seller_org_name: 'Swarnandhra Engineering College',
    seller_rating: 4.8,
    seller_trust_rating: 4.8,
    title: 'Balding OCC (Old Corrugated Containers) Cardboard Bales',
    category: 'Paper & Cardboard',
    description: 'Double-strapped high-density corrugated paper bales from college logistics hub. Moisture content < 10%, zero contamination.',
    images: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80'
    ],
    quantity: 12,
    unit: 'Bales',
    quality_grade: 'Grade A',
    price_per_unit: 120.00,
    sale_type: 'auction',
    location_zone: 'Central Logistics Yard',
    availability_date: '2026-09-12',
    status: 'active',
    verification_status: 'verified',
    authenticity_score: 95,
    batch_code: 'WL-MKT-2026-882',
    views_count: 89,
    bids_count: 5,
    highest_bid: 145.00,
    auction_ends_at: '2026-09-14T18:00:00Z',
    created_at: '2026-09-09T08:30:00Z'
  },
  {
    id: 'mkt-lst-03',
    seller_id: 'usr-citizen-1',
    seller_name: 'Grand Palace Operations',
    seller_org_name: 'Grand Palace Hotel & Resort',
    seller_rating: 4.7,
    seller_trust_rating: 4.7,
    title: 'Purified Organic Compost & Bio-Fertilizer (50kg Bags)',
    category: 'Organic Compost',
    description: 'Aerobic thermophilic compost created from 100% hotel food waste in on-site anaerobic digestion composter. Rich in N-P-K content.',
    images: [
      'https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=800&q=80'
    ],
    quantity: 150,
    unit: 'Units',
    quality_grade: 'Grade B',
    price_per_unit: 6.50,
    sale_type: 'direct_sale',
    location_zone: 'Hospitality Green Unit',
    availability_date: '2026-09-10',
    status: 'active',
    verification_status: 'verified',
    authenticity_score: 92,
    batch_code: 'WL-MKT-2026-883',
    views_count: 65,
    created_at: '2026-09-09T14:15:00Z'
  },
  {
    id: 'mkt-lst-04',
    seller_id: 'usr-recycler-1',
    seller_name: 'CleanTech Eco Polymers',
    seller_org_name: 'CleanTech Materials & Plastics',
    seller_rating: 4.9,
    seller_trust_rating: 4.9,
    title: 'Disassembled E-Waste Circuit Boards & Copper Wire Harvest',
    category: 'Electronics',
    description: 'Sorted Motherboards, RAM sticks, and stripped heavy copper wire bundles from institutional IT decommissioning.',
    images: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80'
    ],
    quantity: 850,
    unit: 'kg',
    quality_grade: 'Grade A',
    price_per_unit: 3.40,
    sale_type: 'auction',
    location_zone: 'E-Waste Recovery Facility',
    availability_date: '2026-09-18',
    status: 'active',
    verification_status: 'pending',
    authenticity_score: 89,
    batch_code: 'WL-MKT-2026-884',
    views_count: 210,
    bids_count: 8,
    highest_bid: 3.90,
    auction_ends_at: '2026-09-16T12:00:00Z',
    created_at: '2026-09-10T11:00:00Z'
  }
];

export const INITIAL_MARKETPLACE_OFFERS: MarketplaceOffer[] = [
  {
    id: 'off-01',
    listing_id: 'mkt-lst-01',
    listing_title: 'High-Density Polyethylene (HDPE) Recycled Flakes',
    buyer_id: 'usr-supervisor-1',
    buyer_name: 'Anil Verma',
    buyer_org_name: 'Swarnandhra Campus Ops',
    offered_price_per_unit: 0.80,
    total_amount: 3600.00,
    status: 'pending',
    message: 'Can take the full 4,500 kg if delivered to Campus Zone 1 by Sept 16.',
    created_at: '2026-09-10T11:20:00Z'
  }
];

export const INITIAL_MARKETPLACE_ORDERS: MarketplaceOrder[] = [
  {
    id: 'mkt-ord-101',
    order_code: 'MKT-ORD-99201',
    listing_id: 'mkt-lst-01',
    listing_title: 'High-Density Polyethylene (HDPE) Recycled Flakes',
    seller_name: 'CleanTech Eco Polymers',
    buyer_name: 'Green Valley Recyclers',
    quantity: 2000,
    unit: 'kg',
    total_price: 1700.00,
    escrow_status: 'funds_held',
    delivery_status: 'in_transit',
    pickup_date: '2026-09-11',
    batch_code: 'WL-MKT-2026-881',
    qr_code_verification: 'VERIFIED_BATCH_MKT-ORD-99201',
    created_at: '2026-09-09T16:00:00Z'
  }
];

export const INITIAL_MARKETPLACE_DISPUTES: MaterialDispute[] = [
  {
    id: 'disp-01',
    order_id: 'mkt-ord-101',
    raised_by_name: 'Green Valley Recyclers',
    reason: 'quantity_mismatch',
    description: 'Weighed shipment at gate scale: actual total was 1,940 kg instead of 2,000 kg (60 kg discrepancy).',
    status: 'under_review',
    created_at: '2026-09-10T14:30:00Z'
  }
];

export const INITIAL_MARKETPLACE_REVIEWS: MarketplaceReview[] = [
  {
    id: 'rev-01',
    target_user_name: 'CleanTech Eco Polymers',
    reviewer_name: 'Anil Verma',
    rating: 5,
    comment: 'Exceptional material quality and clean sorting! Batch matched exact technical specs.',
    created_at: '2026-09-08T18:00:00Z'
  }
];

